// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function ConnectNetworkDevice(arg1:string,arg2:string,arg3:number):Promise<string>;

export function ConnectSerialDevice(arg1:string,arg2:string):Promise<string>;

export function DisconnectDevice(arg1:string):Promise<string>;

export function FetchEventDetails(arg1:string,arg2:number,arg3:string):Promise<main.Event>;

export function FetchEvents(arg1:string,arg2:number):Promise<Array<main.Event>>;

export function GetCalibration(arg1:string):Promise<main.EDMCalibrationData>;

export function GetReliableEDMReading(arg1:string):Promise<main.AveragedEDMReading>;

export function ListSerialPorts():Promise<Array<string>>;

export function MeasureThrow(arg1:string):Promise<string>;

export function MeasureWind(arg1:string):Promise<string>;

export function PostResult(arg1:string,arg2:number,arg3:main.ResultPayload):Promise<void>;

export function ResetCalibration(arg1:string):Promise<void>;

export function SaveCalibration(arg1:string,arg2:main.EDMCalibrationData):Promise<void>;

export function SendToScoreboard(arg1:string):Promise<void>;

export function SetCircleCentre(arg1:string):Promise<main.EDMCalibrationData>;

export function SetDemoMode(arg1:boolean):Promise<void>;

export function SetServerAddress(arg1:string,arg2:number):Promise<void>;

export function StartWindListener(arg1:string,arg2:context.Context):Promise<void>;

export function VerifyCircleEdge(arg1:string):Promise<main.EDMCalibrationData>;
